-- Inventory module
-- Authoritative tables are created by ../INSTALL.sql.
-- Owned tables: inventory_items, inventory_movements, stock_counts
-- Keep this file as a migration placeholder; do not duplicate CREATE TABLE statements here.
