-- Cashier module
-- Authoritative tables are created by ../INSTALL.sql.
-- Owned tables: cashier_shifts, cash_movements, cash_reconciliations
-- Keep this file as a migration placeholder; do not duplicate CREATE TABLE statements here.
