-- Reception module
-- Authoritative tables are created by ../INSTALL.sql.
-- Owned tables: reception_users, reception_records, guest_checkins, guest_checkouts
-- Keep this file as a migration placeholder; do not duplicate CREATE TABLE statements here.
