-- Transport module
-- Authoritative tables are created by ../INSTALL.sql.
-- Owned tables: vehicles, transport_requests, vehicle_logs
-- Keep this file as a migration placeholder; do not duplicate CREATE TABLE statements here.
