-- Hr module
-- Authoritative tables are created by ../INSTALL.sql.
-- Owned tables: staff_profiles, attendance, leave_requests
-- Keep this file as a migration placeholder; do not duplicate CREATE TABLE statements here.
