-- Spa module
-- Authoritative tables are created by ../INSTALL.sql.
-- Owned tables: spa_services, spa_appointments, spa_payments
-- Keep this file as a migration placeholder; do not duplicate CREATE TABLE statements here.
