-- Events module
-- Authoritative tables are created by ../INSTALL.sql.
-- Owned tables: events, event_bookings, event_services
-- Keep this file as a migration placeholder; do not duplicate CREATE TABLE statements here.
