-- Notifications module
-- Authoritative tables are created by ../INSTALL.sql.
-- Owned tables: notifications, notification_preferences, notification_devices
-- Keep this file as a migration placeholder; do not duplicate CREATE TABLE statements here.
