<?php
declare(strict_types=1);

/**
 * Generates (or refreshes) backend-php/vapid.php, the VAPID signing identity
 * for Browser Web Push. Run once on each server:
 *
 *     php tools/make-vapid-keys.php
 *
 * The file it writes is gitignored, exactly like config.php, because whoever
 * holds the private key can send notifications that the hotel's own phones
 * trust. A fresh site with no file simply has push delivery switched off until
 * this script is run; nothing else in the system stops working.
 */

if(PHP_SAPI!=='cli'){ fwrite(STDERR,"Run this from the command line.\n"); exit(1); }

$target=dirname(__DIR__).'/backend-php/vapid.php';
require_once dirname(__DIR__).'/backend-php/app/webpush.php';
\WebPush\ensure_conf();

if(is_readable($target)){
 $old=require $target;
 if(is_array($old)&&isset($old['private'])&&$old['private']!==''){
  fwrite(STDOUT,"backend-php/vapid.php already exists; leaving the keys untouched.\n");
  exit(0);
 }
}

$kp=\WebPush\generate_keypair();
if($kp===null){ fwrite(STDERR,"Could not generate a P-256 key pair. The OpenSSL extension or the openssl program is unavailable.\n"); exit(1); }
$public=rtrim(strtr(base64_encode($kp['raw']),'+/','-_'),'=');

$subject='mailto:notifications@hotelparadiseonthenile.info';
if(isset($old['subject'])&&is_string($old['subject'])&&$old['subject']!=='') $subject=$old['subject'];

$php="<?php\n".
"// The hotel's Browser Web Push identity. Generated by tools/make-vapid-keys.php.\n".
"// Gitignored and never committed: the private key signs the notifications the\n".
"// hotel's own phones trust. Delete the file and run the script again to rotate.\n".
"return [\n".
" 'subject' => ".var_export($subject,true).",\n".
" 'public'  => ".var_export($public,true).",\n".
" 'private' => ".var_export($kp['key'],true).",\n".
"];\n";

if(file_put_contents($target,$php,LOCK_EX)===false){ fwrite(STDERR,"Could not write $target\n"); exit(1); }

fwrite(STDOUT,"Wrote VAPID keys to $target\n");
fwrite(STDOUT,"Public key: $public\n");
fwrite(STDOUT,"Subject: $subject\n");

require_once dirname(__DIR__).'/backend-php/app/webpush.php';
if(!\WebPush\configured()){ fwrite(STDOUT,"Note: push delivery is ready but a push service can only be reached over signed HTTPS by a real phone.\n"); exit(0); }
fwrite(STDOUT,"Web Push sender is configured.\n");
exit(0);